SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTATISTICA;
CREATE DATABASE DBESTATISTICA;
USE DBESTATISTICA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, SEXO CHAR(1)
);

CREATE TABLE ESTATISTICA (	
	HOMEM INT
	, MULHER INT
);

DELIMITER $$
CREATE TRIGGER TR_PESSOA_AI AFTER INSERT ON PESSOA FOR EACH ROW
BEGIN	
    IF NEW.SEXO = 'F' THEN
    UPDATE ESTATISTICA
    SET MULHER = MULHER+1;
    END IF;
    
    IF NEW.SEXO = 'M' THEN
    UPDATE ESTATISTICA
    SET HOMEM = HOMEM + 1;
    END IF;
END $$
CREATE TRIGGER TR_PESSOA_AD AFTER DELETE ON PESSOA FOR EACH ROW
BEGIN
	IF OLD.SEXO = 'F' THEN
		UPDATE ESTATISTICA
        SET MULHER = MULHER -1;
	END IF;
	IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA
        SET HOMEM = HOMEM -1;
	END IF;
END $$

CREATE TRIGGER TR_PESSOA_AU AFTER UPDATE ON PESSOA FOR EACH ROW
BEGIN
	-- VERIFICAR O VALOR ANTIGO
        IF OLD.SEXO = 'F' THEN
			UPDATE ESTATISTICA
            SET MULHER = MULHER -1;
        END IF;
        IF OLD.SEXO = 'M' THEN
			UPDATE ESTATISTICA
            SET HOMEM = HOMEM -1;
            END IF;
	-- VERIFICAR O VALOR NOVO
		IF NEW.SEXO = 'F' THEN
			UPDATE ESTATISTICA
            SET MULHER = MULHER +1;
            END IF;
		IF NEW.SEXO = 'M' THEN
			UPDATE ESTATISTICA
            SET HOMEM = HOMEM +1;
		END IF;
END $$

CREATE TRIGGER TR_PESSOA_BI BEFORE INSERT ON PESSOA FOR EACH ROW
BEGIN 
	-- REGRA SE O CAMPO É VAZIO
		IF NEW.SEXO IS NULL THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = ' Sexo deve ser preenchido';
        END IF;
        

	-- REGRA SE O CAMPO TEM VALOR DIFERENTE DE M OU fetch
		IF NEW.SEXO NOT IN ('M','F') THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = ' Sexo inválido';
        END IF;
        
        -- COLOCANDO O CAMPO SEMPRE EM MAIUSCULO
        SET NEW.SEXO = UPPER(NEW.SEXO);
       
END $$
	CREATE TRIGGER TR_PESSOA_BU BEFORE UPDATE ON PESSOA FOR EACH ROW
BEGIN 
	-- REGRA SE O CAMPO É VAZIO
		IF NEW.SEXO IS NULL THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = ' Sexo deve ser preenchido';
        END IF;
        

	-- REGRA SE O CAMPO TEM VALOR DIFERENTE DE M OU fetch
		IF NEW.SEXO NOT IN ('M','F') THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = ' Sexo inválido';
        END IF;
        
        -- COLOCANDO O CAMPO SEMPRE EM MAIUSCULO
        SET NEW.SEXO = UPPER(NEW.SEXO);
	
END $$
DELIMITER ;

INSERT INTO ESTATISTICA(HOMEM, MULHER) VALUES(0,0);

SELECT * FROM PESSOA;
SELECT* FROM ESTATISTICA;
INSERT INTO PESSOA (NOME,SEXO) VALUES ('ANA','F');
INSERT INTO PESSOA(NOME,SEXO)VALUES('CARLOS','m');
DELETE FROM PESSOA WHERE NOME = 'CARLOS';
